[window]
dynamic_title = false
decorations= "Full"
opacity = 1.0
blur = false
padding.x = 5
padding.y = 10

[env]
TERM = "xterm-256color"

[terminal]
shell.program = "wsl"
shell.args = ["--cd ~"]

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
normal.style = "SemiBold"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
bold.style = "Bold"
italic.family = "JetBrainsMonoNL Nerd Font Mono"
italic.style = "Bold Italic"
bold_italic.family = "JetBrainsMonoNL Nerd Font Mono"

size = 13

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "C", mods = "Control", action = "Copy" },
]

# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors
[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#706e86'
red = '#eb6f92'
blue = '#31748f'
yellow = '#f6c177'
green = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.bright]
black = '#706e86'
red = '#eb6f92'
blue = '#31748f'
yellow = '#f6c177'
green = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }
